version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 4000:80
    volumes: 
      - ./nginx_server/default.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
    depends_on: 
      - app_project
  mongo_db:
    image: mongo
    volumes:
      - my-app-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  app_project:
    image: my-app-project
    environment:
      - MONGO_IP=${MONGO_IP}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on: 
      - mongo_db
      - redis_db
  redis_db:
    image: redis
volumes: 
  my-app-volume: 